name: Android Firebase App Distribution

on:
  workflow_dispatch:
    inputs:
      build-number:
        description: 'Build number'
        required: true
        default: '1'

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Decrypt Keystore
        id: keystore_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: "keystore.jks"
          fileDir: './main/folder/subfolder/'
          encodedString: ${{ secrets.KEYSTORE_ENCODED }}

      - name: Build Android Release APK
        run: ./gradlew :androidApp:packageReleaseUniversalApk
        env:
          KEYSTORE_FILE: ${{ steps.keystore_file.outputs.filePath }}
          KEYSTORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: androidApp/build/outputs/

  distribute_to_firebase:
    needs: [ build_android ]
    runs-on: ubuntu-latest
    steps:
      - name: Download Android APK
        uses: actions/download-artifact@v3
        with:
          name: android-apk
      - name: Distribute to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: br.com.developes.sdui.android
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: /home/runner/work/compose-multiplatform-sdui/compose-multiplatform-sdui/androidApp/build/outputs/apk_from_bundle/release/androidApp-release-universal-unsigned.apk