name: Build and Distribute Android App to Firebase App Distribution

on:
  workflow_dispatch:

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Android Release APK
        run: ./gradlew :androidApp:assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: androidApp/build/outputs/apk/release/androidApp-release.apk

  distribute_android_to_firebase:
    needs: [ build_android ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Android APK
        uses: actions/download-artifact@v3
        with:
          name: android-apk
      - name: Distribute to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: br.com.developes.sdui.android
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: android-apk/androidApp-release.apk