name: Build and Distribute

on: workflow_dispatch

jobs:
  build_and_distribute:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 7.2
      - uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/keystore.jks'
          encodedString: ${{ secrets.KEYSTORE_ENCODED }}

      - name: Build Android
        run: ./gradlew androidApp:assembleRelease
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Build iOS
        run: xcodebuild -workspace iosApp/iosApp.xcworkspace -scheme iosApp -destination 'generic/platform=iOS' archive -archivePath build/iosApp.xcarchive

      - name: Export iOS IPA
        run: xcodebuild -exportArchive -archivePath build/iosApp.xcarchive -exportPath build -exportOptionsPlist iosApp/ExportOptions.plist

      - name: Distribute to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: androidApp/build/outputs/apk/release/androidApp-release.apk,build/iosApp.ipa